kid_max_age : 17
student_min_age : 18
student_max_age : 25
old_min_age : 65
old_max_age : 99
adult_min_age : 18
adult_max_age : 64
young_adult_min_age : 18
young_adult_max_age : 35
max_age_to_be_parent : 64
max_household_size : 8

default_household_compositions:
  type_1:
    label: "0 0 0 0 2"
    composition: [0, 0, 0, 0, 2]
    household: "old"
  type_2:
    label: "0 0 0 2 0"
    composition: [0, 0, 0, 2, 0]
    household: "nokids"
  type_3:
    label: "0 0 0 0 1"
    composition: [0, 0, 0, 0, 1]
    household: "old"
  type_4:
    label: "0 0 0 1 0"
    composition: [0, 0, 0, 1, 0]
    household: "nokids"
  type_5:
    label: "1 0 >=0 2 0"
    composition: [1, 0, 0.5, 2, 0]
    household: "family"
  type_6:
    label: ">=2 0 >=0 2 0"
    composition: [2.5, 0, 0.5, 2, 0]
    household: "family"
  type_7:
    label: "0 0 >=1 2 0"
    composition: [0, 0, 1.5, 2, 0]
    household: "ya_parents"
  type_8:
    label: "1 0 >=0 1 0"
    composition: [1, 0, 0.5, 1, 0]
    household: "family"
  type_9:
    label: ">=2 0 >=0 1 0"
    composition: [2.5, 0, 0.5, 1, 0]
    household: "family"
  type_10:
    label: "0 0 >=1 1 0"
    composition: [0, 0, 1.5, 1, 0]
    household: "ya_parents"
  type_11:
    label: "1 0 >=0 >=1 >=0"
    composition: [1, 0, 0.5, 1.5, 0.5]
    household: "family"
  type_12:
    label: ">=2 0 >=0 >=1 >=0"
    composition: [2.5, 0, 0.5, 1.5, 0.5]
    household: "family"
  type_13:
    label: "0 >=1 0 0 0"
    composition: [0, 1.5, 0, 0, 0]
    household: "student"
  type_14:
    label: "0 0 0 0 >=2"
    composition: [0, 0, 0, 0, 2.5]
    household: "old"
  type_15:
    label: "0 0 >=0 >=0 >=0"
    composition: [0, 0, 0.5, 0.5, 0.5]
    household: "other"
  type_16:
    label: ">=0 >=0 >=0 >=0 >=0"
    composition: [0.5, 0.5, 0.5, 0.5, 0.5]
    household: "communal"

ignore_orphans: False
