name: Run linting and sanity checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openmpi-bin
        sudo apt install -y libhdf5-dev
        sudo apt install -y libopenmpi-dev

    - name: Install JUNE
      run: |
        python -m pip install --upgrade pip
        python setup.py install

    - name: Lint with black and flake8
      run: |
        pip install flake8
        pip install black
        black --check june
        black --check test_june
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --show-source --statistics
        # flake8 .
        flake8 june
        flake8 test_june

    - name: Get JUNE data
      run: bash scripts/get_june_data.sh

    - name: Test with pytest
      run: |
        cd test_june
        pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Test all cells in ipynb for errors
      run: |
        jupyter nbconvert --to notebook --inplace --execute Notebooks/quickstart.ipynb
